#ifndef ENV_H
#define ENV_H

#include "libmcu.h"

#define TIMER_PRESCALE 1
#define TIMER_AUTORELOAD 1248

#define INVERSOR_ADC_CHANNEL_1_GPIO 6
#define INVERSOR_ADC_CHANNEL_2_GPIO 7
#define INVERSOR_ADC_CHANNEL_3_GPIO -1

#define IHM_GPIOx_ON_OFF GPIOB
#define IHM_BUTTON_ON_OFF_GPIO 4

#define IHM_GPIOx_SETPOINT GPIOB
#define IHM_BUTTON_SETPOINT_GPIO 0

#define IHM_GPIOx_KP GPIOB
#define IHM_BUTTON_KP_GPIO 1

#define IHM_GPIOx_KI GPIOB
#define IHM_BUTTON_KI_GPIO 2

#endif